/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "progressiveEnhancementExample": "progressiveEnhancementExample",
  "timeSinceOpened": "timeSinceOpened",
  "welcomeToPikku": "welcomeToPikku",
  "helloWorld": "helloWorld",
  "rpcTest": "rpcTest",
  "rpcCaller": "rpcCaller"
})